default: &default
  adapter: postgresql
  encoding: unicode
  database: market_place_api_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: 
  password: 

development:
  <<: *default
  database: market_place_api_development

test:
  <<: *default
  database: market_place_api_test

production:
  <<: *default
  database: market_place_api_production
  username: danilo
  password: <%= ENV['market_place_api_DATABASE_PASSWORD'] %>
